### ISSUE TITLE
Add timing information to debug output

### ISSUE THREAD

**Issue by dkarlovi** [nuncanada/vagrant-rsync-only-changed#2]
When I run `vagrant rsync-auto --debug`, it get 

```
INFO rsync-auto: Time spent in rsync: 2.648954147 (in seconds)
```

as the last line of output after each sync event. You should add it too, this would enable us to see the speed difference quite plainly.

**Comment by dkarlovi** [comment]
See https://github.com/mitchellh/vagrant/pull/6568/files#diff-de2df059af671fe3c2f160dacc56994dR191

**Comment by nuncanada** [comment]
Done in version 0.8.2
Update to version 0.8.3 it has a check if you have at least rsync version 3.1.0, that is important to allow to use the --from-files option with deleted files

**Comment by dkarlovi** [comment]
Great, [I've tested it against default implementation](https://github.com/mitchellh/vagrant/issues/6856#issuecomment-171321555) and am getting quite a boost. This means your functionality works as expected and you should try and get it merged upstream.

Thank you for your work!
